# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2025
customText = "ä¹ˆä¹ˆå“’"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸ·"
subtitle = "æ³¢æ¯”å“ˆå“ˆå“ˆçš„åšå®¢"

[sidebar.avatar]
enabled = true
local = true
src = "img/bobby.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "waline"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = "http://waline-delta-black.vercel.app/"
lang = "zh-CN"
visitor = ""
avatar = ""
emoji = [
    "https://npm.elemecdn.com/@waline/emojis@1.1.0/bilibili",
    "https://npm.elemecdn.com/@waline/emojis@1.1.0/bmoji", 
    "https://npm.elemecdn.com/@waline/emojis@1.1.0/weibo"
]
requiredMeta = ["name", "email", "url"]
placeholder = "æ¬¢è¿ç•™ä¸‹å®è´µçš„è¯„è®ºï¼"

[comments.waline.locale]
admin = "æ³¢æ¯”"
sofa = "è¿˜æ²¡æœ‰äººè¯„è®ºå“¦ï¼å¿«æ¥æŠ¢æ²™å‘å§~"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
